/*ARRAY DE PELICULAS */
const peliculas=[
    {
    ID:"1",
    btn:"1",
    titulo:"Unboxed",
    imagen:"./unboxed-200x300.jpg",
    genero:"terror",
    año:"2022",
    duracion:"1hs 13min",
    director:"David Becerra, Eddie del Carmen",
    actores:"Bryan Dijols, Elaine del Valle, Katherine",
    urlpeli:"./peliculas/unboxedRef.html",
    descripcion:"Laura Díaz es una prometedora influencer presionada por un patrocinador VIP para que ofrezca su mejor actuación en una retransmisión en directo de Halloween...."
    },
    {
    ID:"2",
    btn:"2",
    titulo:"Corazones mal heridos",
    imagen:"./corazonesMalheridos200x300.jpg",
    genero:"Drama",
    año:"2022",
    duracion:"2h 2min",
    director:"Ellizabeth Allen,Ishai Setton",
    actores:"Benjamín Del Cerro, A.J.Tannen, Alex Wexo, Anna Marusich",
    urlpeli:"./peliculas/CorazonesmalheridosRef.html",
    descripcion:"Una aspirante a música y un marine a punto de irse a Irak deciden casarse por conveniencia. Pero una tragedia pronto convierte su relación falsa en algo muy real."
    },
    {
    ID:"3",
    btn:"3",    
    titulo:"Dc liga",
    imagen:"./dc-liga-de-supermascotas-200x300.jpg",
    genero:"Accion",
    año:"2022",
    duracion:"1hs 46min",
    director:"Jared Stern"||"Sam Levine",
    actores:"Alfred Molina, Amanda Manes ",
    urlpeli:"#",
    descripcion:"El perro de Superman se une al gato volador para impedir el crimen mientras Superman se va de vacaciones."
    },
    {
    ID:"4",
    btn:"4",
    titulo:"Linterna verde",
    imagen:"./linterna-verde-200x300.jpg",
    genero:"Animacion",
    año:"2022",
    duracion:"1hs 23min",
    director:"Anna Gutto",
    actores:"Aldis Hodge, Bryan Bloom",
    urlpeli:"#",
    descripcion:"El ex soldado John Stewart se une a los Green Lanterns, una fuerza de patrulla espacial"
    },
    {
    ID:"5",
    btn:"5",
    titulo:"Mi peluqueria en rio",
    imagen:"./mi-peluqueria-en-rio-200x300.jpg",
    genero:"Comedia",
    año:"2022",
    duracion:"1hs 30min",
    director:"Leticia Prisco, Rodrigo França",
    actores:" Bruno Jablonski, Jeniffer Dias",
    urlpeli:"#",
    descripcion:"Un hijo abnegado decide echarle una mano a su madre, que está a punto de perder su peluquería. Al hacerlo, se destapa como el estilista más talentoso de la zona."
    },
    {
    ID:"6",
    btn:"6",
    titulo:"Not okay",
    imagen:"./not-okay-200x300.jpg",
    genero:"Comedia",
    año:"2022",
    duracion:"1hs 40min",
    director:"Quinn Shephard",
    actores:"Blaise Corrigan, Dash Perry", 
    urlpeli:"#",
    descripcion:"Una joven desesperada por amigos y fama, finge un viaje a París para actualizar su presencia en las redes sociales. En el mundo real tiene lugar un incidente aterrador que se convierte en parte del viaje imaginario y que ella deberá resolver."
    },
    {
    ID:"7",
    btn:"7",
    titulo:"Paradise highway",
    imagen:"./paradise-highway-200x300.jpg",
    genero:"Thriller",
    año:"2022",
    duracion:"1hs 55min",
    director:"Anna Gutto",
    actores:"Calvin Williams, Cameron Monaghan",
    urlpeli:"#",
    descripcion:"Una camionera se ve obligada a contrabandear un cargamento ilícito para salvar a su hermano de una mortífera banda carcelaria. "
    },
    {
    ID:"8",
    btn:"8",
    titulo:"Pipa",
    imagen:"./pipa-200x300.jpg",
    genero:"Crimen",
    año:"2022",
    duracion:"1h 56m",
    director:"Alejandro Montiel",
    actores:"Benjamín Del Cerro, Inés Estévez, Luisana Lopilato",
    urlpeli:"#",
    descripcion:"Manuela «Pipa» Pelari ya no es la misma. La mujer dura y aguerrida que sobrevivió a su paso por la Policía a fuerza de romper las reglas y guardar secretos oscuros decidió cambiar de vida. "
    },     
]